# Generated by Django 2.2 on 2020-06-17 23:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='initial_design',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimated design hours'),
        ),
        migrations.AddField(
            model_name='log',
            name='initial_development',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimated development hours'),
        ),
        migrations.AddField(
            model_name='log',
            name='initial_testing',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Estimated testing hours'),
        ),
        migrations.AddField(
            model_name='log',
            name='result_design',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Actual design hours'),
        ),
        migrations.AddField(
            model_name='log',
            name='result_development',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Actual development hours'),
        ),
        migrations.AddField(
            model_name='log',
            name='result_testing',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Actual testing hours'),
        ),
    ]
