# Generated by Django 2.2 on 2020-06-19 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200620_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_date', models.DateField(verbose_name='Date of attachment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=16, verbose_name='Tag name')),
                ('project', models.ManyToManyField(through='projects.ProjectsTags', to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='projectstags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Tag'),
        ),
    ]
