# Generated by Django 2.2 on 2020-06-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200620_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectsTags',
            new_name='ProjectTag',
        ),
    ]
