# Generated by Django 2.2 on 2020-06-24 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200624_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='initial_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Initial design hours'),
        ),
        migrations.AlterField(
            model_name='log',
            name='initial_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Initial development hours'),
        ),
        migrations.AlterField(
            model_name='log',
            name='initial_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Initial testing hours'),
        ),
        migrations.AlterField(
            model_name='log',
            name='result_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Result design hours'),
        ),
        migrations.AlterField(
            model_name='log',
            name='result_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Result development hours'),
        ),
        migrations.AlterField(
            model_name='log',
            name='result_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='Result testing hours'),
        ),
    ]
