# Generated by Django 2.2 on 2020-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200625_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='tagname',
        ),
    ]
